# Generated by Django 5.2.8 on 2025-11-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0002_nomination_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominationvote",
            name="nomination",
            field=models.ForeignKey(
                db_column="nomination_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="nominations.nomination",
            ),
        ),
        migrations.AlterField(
            model_name="nominationvote",
            name="option",
            field=models.ForeignKey(
                db_column="option_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="nominations.nominationoption",
            ),
        ),
    ]
