# Generated by Django 5.2.8 on 2025-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0004_voting_and_nomination_voting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="Стабильный идентификатор голосования; не меняйте после создания.",
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
