# Generated by Django 5.2.8 on 2026-01-12 21:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("TENANT", "TENANT"),
                            ("COMMUNITY", "COMMUNITY"),
                            ("TEAM", "TEAM"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_id", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "location_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("location_url", models.URLField(blank=True, null=True)),
                ("game_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("community", "community"),
                            ("team", "team"),
                            ("private", "private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events_event",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "starts_at"],
                        name="events_event_tenant_start_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "ends_at"],
                        name="events_event_tenant_end_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "scope_type", "scope_id"],
                        name="events_event_tenant_scope_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("payload", models.JSONField(default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "events_outbox",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "occurred_at"],
                        name="events_outbox_tenant_occ_idx",
                    ),
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="events_outbox_type_occ_idx",
                    ),
                    models.Index(
                        fields=["published_at"], name="events_outbox_published_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("marked_by", models.UUIDField()),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "events_attendance",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "event"],
                        name="events_att_tenant_event_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "user_id"],
                        name="events_att_tenant_user_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "event", "user_id"),
                        name="events_attendance_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "interested"),
                            ("going", "going"),
                            ("not_going", "not_going"),
                        ],
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "events_rsvp",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "event"],
                        name="events_rsvp_tenant_event_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "user_id"],
                        name="events_rsvp_tenant_user_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "event", "user_id"),
                        name="events_rsvp_unique",
                    )
                ],
            },
        ),
    ]
