# Generated by Django 5.2.8 on 2026-01-12 20:54

import django.db.models.deletion
import django.utils.timezone
import updspaceid.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usid_tenant',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_slug', models.SlugField(max_length=64)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by_user_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usid_application',
                'indexes': [models.Index(fields=['tenant_slug', 'status'], name='usid_app_tenant_status_idx'), models.Index(fields=['status', 'created_at'], name='usid_app_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('banned', 'banned'), ('migrated_unclaimed', 'migrated_unclaimed')], default='migrated_unclaimed', max_length=32)),
                ('system_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usid_user',
                'indexes': [models.Index(fields=['email'], name='usid_user_email_idx'), models.Index(fields=['status'], name='usid_user_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=16)),
                ('base_role', models.CharField(default='member', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='updspaceid.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_tenant_membership',
                'indexes': [models.Index(fields=['tenant', 'status'], name='usid_memb_tenant_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='usid_memb_user_tenant_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('state', models.CharField(default=updspaceid.models.generate_token_urlsafe, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('nonce', models.CharField(default=updspaceid.models.generate_token_urlsafe, max_length=128)),
                ('provider', models.CharField(choices=[('github', 'github'), ('discord', 'discord'), ('steam', 'steam')], max_length=16)),
                ('purpose', models.CharField(choices=[('link', 'link'), ('login', 'login')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_oauth_state',
                'indexes': [models.Index(fields=['provider', 'purpose', 'expires_at'], name='usid_oauth_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_system', models.CharField(max_length=64)),
                ('old_user_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_migration_map',
                'constraints': [models.UniqueConstraint(fields=('old_system', 'old_user_id'), name='usid_migration_old_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('token', models.CharField(default=updspaceid.models.generate_token_urlsafe, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_magic_link_token',
                'indexes': [models.Index(fields=['expires_at'], name='usid_magic_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdSession',
            fields=[
                ('token', models.CharField(default=updspaceid.models.generate_token_urlsafe, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_session',
                'indexes': [models.Index(fields=['expires_at'], name='usid_session_exp_idx'), models.Index(fields=['user', 'expires_at'], name='usid_session_user_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'github'), ('discord', 'discord'), ('steam', 'steam')], max_length=16)),
                ('subject', models.CharField(max_length=128)),
                ('tokens_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_external_identity',
                'indexes': [models.Index(fields=['provider'], name='usid_ext_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='usid_ext_provider_subject_uniq'), models.UniqueConstraint(fields=('user', 'provider'), name='usid_ext_user_provider_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=128)),
                ('meta_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updspaceid.tenant')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_audit_log',
                'indexes': [models.Index(fields=['action', 'created_at'], name='usid_audit_action_created_idx'), models.Index(fields=['tenant', 'created_at'], name='usid_audit_tenant_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('token', models.CharField(default=updspaceid.models.generate_token_urlsafe, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updspaceid.user')),
            ],
            options={
                'db_table': 'usid_activation_token',
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='usid_activation_tenant_exp_idx'), models.Index(fields=['expires_at'], name='usid_activation_exp_idx')],
            },
        ),
    ]
