# Generated by Django 6.0.3 on 2026-04-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dashboardwidget'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentwidget',
            new_name='core_conten_tenant__95a6f7_idx',
            old_name='core_conten_tenant__widget_idx',
        ),
        migrations.RenameIndex(
            model_name='contentwidget',
            new_name='core_conten_placeme_b613b2_idx',
            old_name='core_conten_placem_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardlayout',
            new_name='core_dashbo_tenant__ea9cd7_idx',
            old_name='core_dashbo_tenant__ec9837_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardlayout',
            new_name='core_dashbo_tenant__4eeb1e_idx',
            old_name='core_dashbo_tenant__1475fb_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardwidget',
            new_name='core_dashbo_tenant__006e28_idx',
            old_name='core_dashbo_tenant__8cd4a2_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardwidget',
            new_name='core_dashbo_layout__425690_idx',
            old_name='core_dashbo_layout__f9700e_idx',
        ),
        migrations.RenameIndex(
            model_name='homepagemodal',
            new_name='core_homepa_tenant__ef697b_idx',
            old_name='core_homepa_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='homepagemodal',
            new_name='core_homepa_start_d_b2e51f_idx',
            old_name='core_homepa_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='modalanalytics',
            new_name='core_modala_modal_i_2c4107_idx',
            old_name='core_modala_modal_event_idx',
        ),
        migrations.RenameIndex(
            model_name='modalanalytics',
            new_name='core_modala_tenant__73c562_idx',
            old_name='core_modala_tenant_time_idx',
        ),
        migrations.RenameIndex(
            model_name='userpreference',
            new_name='core_userpr_user_id_46a32d_idx',
            old_name='core_userpr_user_id_a7b123_idx',
        ),
    ]
