# Generated by Django 5.2.8 on 2026-01-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_voting', '0001_initial'),
    ]

    operations = [
    ]
