# Generated by Django 5.2.8 on 2026-01-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_voting', '0002_ensure_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nomination',
            new_name='v_nom_poll_sort_idx',
            old_name='voting_nomination_poll_sort_idx',
        ),
    ]
