# Generated by Django 6.0.1 on 2026-01-16 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_voting', '0007_poll_invite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='voting_vote_unique_per_nomination',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollinvite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pollinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pollparticipant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
