# Generated by Django 6.0.1 on 2026-01-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidctoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
