export const profileHubStrings = {
  bioMissing: 'Добавьте описание профиля — так людям проще понять, кто вы.',
  showMore: 'Показать полностью',
  collapse: 'Свернуть',
  composerPlaceholder: 'Что нового?',
  composerPublish: 'Опубликовать',
  composerNoPermission: 'У вас нет прав на публикацию в этом tenant’е. Обратитесь к администратору.',
  publishSuccess: 'Опубликовано',
  publishError: 'Не удалось опубликовать. Попробуйте ещё раз.',
  filters: {
    posts: 'Посты',
    activity: 'Активность',
    media: 'Медиа',
    pinned: 'Закреплённое',
  },
  feedEmptySelf: 'Пока здесь пусто. Напишите свой первый пост.',
  feedEmptyOther: 'Пока нет публикаций.',
  feedCreatePost: 'Создать пост',
  feedNoPermission: 'У вас нет прав на просмотр публикаций в этом разделе.',
  feedErrorTitle: 'Не удалось загрузить ленту',
  feedErrorHint: 'Проверьте подключение и попробуйте ещё раз.',
  retry: 'Повторить',
  loadMore: 'Показать ещё',
  listPage: {
    searchBacklogHint: 'Поиск/фильтр появится в следующей итерации.',
    loading: 'Загрузка...',
    errorTitle: 'Не удалось загрузить список',
  },
  about: {
    title: 'О себе',
    empty: 'Нет информации',
    edit: 'Редактировать',
    language: 'Язык',
    timezone: 'Часовой пояс',
  },
  achievements: {
    title: 'Достижения',
    empty: 'Пока нет достижений',
    showAll: 'Все достижения',
  },
  following: {
    title: 'Подписки',
    empty: 'Пока нет подписок',
    showAll: 'Показать все',
  },
  followers: {
    title: 'Подписчики',
    empty: 'Пока нет подписчиков',
    showAll: 'Показать все',
  },
  communities: {
    title: 'Сообщества',
    empty: 'Пока нет сообществ',
    showAll: 'Показать все',
  },
  friends: {
    title: 'Друзья',
    empty: 'Пока нет друзей',
    showAll: 'Показать все',
  },
  completion: {
    title: 'Заполнение профиля',
    hint: 'Заполните профиль — так вас проще найти и узнать.',
    cta: 'Заполнить профиль',
    checklist: {
      avatar: 'Добавьте фото',
      bio: 'Заполните описание',
      contacts: 'Укажите контакты',
      follows: 'Подпишитесь на людей',
      firstPost: 'Опубликуйте первый пост',
    },
  },
  common: {
    editProfile: 'Редактировать профиль',
    follow: 'Подписаться',
    unfollow: 'Отписаться',
    message: 'Сообщение',
    copyLink: 'Скопировать ссылку',
    copied: 'Ссылка скопирована',
    copyFailed: 'Не удалось скопировать ссылку',
    privacySettings: 'Перейти к настройкам приватности',
    toHome: 'На главную',
  },
} as const;
