# Generated by Django 5.2.8 on 2026-01-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bff', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bffsession',
            new_name='bff_bffsess_tenant__82ed8e_idx',
            old_name='bff_bffses_tenant__4ae4f9_idx',
        ),
        migrations.AddIndex(
            model_name='bffsession',
            index=models.Index(fields=['expires_at'], name='bff_bffsess_expires_9ab657_idx'),
        ),
    ]
