# Generated by Django 6.0.1 on 2026-01-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersessiontoken',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersessiontoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSessionMeta',
        ),
        migrations.DeleteModel(
            name='UserSessionToken',
        ),
    ]
