# Generated by Django 5.2.8 on 2026-01-12 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('service', models.CharField(choices=[('portal', 'portal'), ('voting', 'voting'), ('events', 'events'), ('activity', 'activity')], max_length=32)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'indexes': [models.Index(fields=['service'], name='access_cont_service_66e700_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('service', models.CharField(choices=[('portal', 'portal'), ('voting', 'voting'), ('events', 'events'), ('activity', 'activity')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_system_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'indexes': [models.Index(fields=['tenant_id', 'service'], name='access_cont_tenant__c96878_idx'), models.Index(fields=['service'], name='access_cont_service_202824_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'service', 'name'), name='ac_role_unique_per_tenant_service_name'), models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', True)), fields=('service', 'name'), name='ac_role_unique_global_template')],
            },
        ),
        migrations.CreateModel(
            name='PolicyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('deny', 'deny'), ('allow', 'allow')], max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(blank=True, db_column='permission_key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_overrides', to='access_control.permission')),
            ],
            options={
                'verbose_name': 'Policy override',
                'verbose_name_plural': 'Policy overrides',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='access_cont_tenant__669f69_idx'), models.Index(fields=['tenant_id', 'user_id', 'action'], name='access_cont_tenant__1a0858_idx'), models.Index(fields=['tenant_id', 'user_id', 'action', 'permission'], name='access_cont_tenant__fe809b_idx'), models.Index(fields=['expires_at'], name='access_cont_expires_238600_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('TENANT', 'TENANT'), ('COMMUNITY', 'COMMUNITY'), ('TEAM', 'TEAM'), ('SERVICE', 'SERVICE')], db_index=True, max_length=16)),
                ('scope_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='access_control.role')),
            ],
            options={
                'verbose_name': 'Role binding',
                'verbose_name_plural': 'Role bindings',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='access_cont_tenant__a7dec4_idx'), models.Index(fields=['tenant_id', 'user_id', 'scope_type', 'scope_id'], name='access_cont_tenant__32c162_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'user_id', 'scope_type', 'scope_id', 'role'), name='ac_role_binding_unique')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_key', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.role')),
            ],
            options={
                'verbose_name': 'Role permission',
                'verbose_name_plural': 'Role permissions',
                'indexes': [models.Index(fields=['role'], name='access_cont_role_id_392203_idx'), models.Index(fields=['permission'], name='access_cont_permiss_3a66de_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='ac_role_permission_unique')],
            },
        ),
    ]
