# Generated by Django 5.2.8 on 2026-01-12 21:58

from django.db import migrations
from access_control.permissions_mvp import MVP_PERMISSIONS

def forwards(apps, schema_editor):
    Permission = apps.get_model("access_control", "Permission")
    for spec in MVP_PERMISSIONS:
        Permission.objects.update_or_create(
            key=spec.key,
            defaults={
                "description": spec.description,
                "service": spec.service
            }
        )

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_seed_mvp_permissions'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
