# Generated by Django 6.0.1 on 2026-01-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_tenant_admin_audit_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantadminauditevent',
            new_name='access_cont_tenant__229ff0_idx',
            old_name='access__tenantadmin_tenant_id_action_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantadminauditevent',
            new_name='access_cont_tenant__2de65f_idx',
            old_name='access__tenantadmin_tenant_id_created_at_idx',
        ),
    ]
