# Generated by Django 5.2.8 on 2026-02-03

from django.db import migrations
from access_control.permissions_mvp import MVP_PERMISSIONS


def forwards(apps, schema_editor):
    Permission = apps.get_model("access_control", "Permission")
    for spec in MVP_PERMISSIONS:
        Permission.objects.update_or_create(
            key=spec.key,
            defaults={
                "description": spec.description,
                "service": spec.service,
            },
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0005_rename_access__tenantadmin_tenant_id_action_idx_access_cont_tenant__229ff0_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
