# Generated by Django 6.0.2 on 2026-02-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_seed_default_member_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='service',
            field=models.CharField(choices=[('portal', 'portal'), ('voting', 'voting'), ('events', 'events'), ('activity', 'activity'), ('gamification', 'gamification')], max_length=32),
        ),
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.CharField(choices=[('portal', 'portal'), ('voting', 'voting'), ('events', 'events'), ('activity', 'activity'), ('gamification', 'gamification')], max_length=32),
        ),
    ]
