# Generated by Django 6.0.2 on 2026-02-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0012_rollout_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experiment',
            new_name='access_cont_key_a8bf02_idx',
            old_name='access_cont_key_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='experiment',
            new_name='access_cont_tenant__a22df8_idx',
            old_name='access_cont_tenant_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='experiment',
            new_name='access_cont_enabled_b1c181_idx',
            old_name='access_cont_enabled_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='access_cont_key_27ef2f_idx',
            old_name='access_cont_key_ff_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='access_cont_tenant__97ad12_idx',
            old_name='access_cont_tenant_ff_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='access_cont_enabled_fd9985_idx',
            old_name='access_cont_enabled_ff_idx',
        ),
        migrations.RenameIndex(
            model_name='killswitch',
            new_name='access_cont_feature_f65919_idx',
            old_name='access_cont_fkey_ks_idx',
        ),
        migrations.RenameIndex(
            model_name='killswitch',
            new_name='access_cont_active_f74d85_idx',
            old_name='access_cont_active_ks_idx',
        ),
        migrations.RenameIndex(
            model_name='rolloutauditlog',
            new_name='access_cont_tenant__3f4d81_idx',
            old_name='access_cont_ral_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='rolloutauditlog',
            new_name='access_cont_entity__4305da_idx',
            old_name='access_cont_ral_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='rolloutauditlog',
            new_name='access_cont_created_d25d77_idx',
            old_name='access_cont_ral_created_idx',
        ),
    ]
