# Generated by Django 5.2.8 on 2026-04-03 13:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        help_text="Theme mode: light, dark, or auto (follows system preference)",
                        max_length=10,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#8B5CF6",
                        help_text="Accent color in hex format (e.g., #8B5CF6 for purple)",
                        max_length=7,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        help_text="Font size: small, medium, or large",
                        max_length=10,
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False,
                        help_text="Enable high contrast mode for better readability",
                    ),
                ),
                (
                    "reduce_motion",
                    models.BooleanField(
                        default=False, help_text="Reduce animations for accessibility"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Русский")],
                        default="en",
                        help_text="Interface language",
                        max_length=5,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone (e.g., Europe/Moscow, America/New_York)",
                        max_length=64,
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Notification preferences (delivery channels, types, frequency)",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "Members Only"),
                            ("private", "Private"),
                        ],
                        default="members",
                        help_text="Who can see user profile",
                        max_length=10,
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=True, help_text="Display online status to others"
                    ),
                ),
                (
                    "show_vote_history",
                    models.BooleanField(
                        default=False, help_text="Display voting history on profile"
                    ),
                ),
                (
                    "share_activity",
                    models.BooleanField(
                        default=True, help_text="Share activity in community feed"
                    ),
                ),
                (
                    "allow_mentions",
                    models.BooleanField(
                        default=True, help_text="Allow other users to @mention you"
                    ),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Collect analytics and usage data (required for platform)",
                    ),
                ),
                (
                    "recommendations_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable personalized recommendations based on activity",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "indexes": [
                    models.Index(
                        fields=["user_id", "tenant_id"],
                        name="personaliza_user_id_cfef0a_idx",
                    ),
                    models.Index(
                        fields=["tenant_id"], name="personaliza_tenant__1e2194_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "tenant_id"),
                        name="unique_user_tenant_preference",
                    )
                ],
            },
        ),
    ]
