# Generated by Django 5.2.8 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="theme_source",
            field=models.CharField(
                choices=[("portal", "Portal"), ("id", "Identity Provider")],
                default="portal",
                help_text="Theme source: portal preference or inherited from ID",
                max_length=10,
            ),
        ),
    ]
