# Generated by Django 5.2.8 on 2026-01-12 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "portal_community",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "portal_tenant",
                "indexes": [
                    models.Index(fields=["slug"], name="portal_tenant_slug_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("archived", "archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="portal.community",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_team",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("community", "community"),
                            ("team", "team"),
                            ("private", "private"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="portal.community",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="portal.team",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_post",
            },
        ),
        migrations.CreateModel(
            name="PortalProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_profile",
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("role_hint", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="portal.community",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_community_membership",
            },
        ),
        migrations.AddField(
            model_name="community",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communities",
                to="portal.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("role_hint", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="portal.team",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_team_membership",
                "indexes": [
                    models.Index(fields=["tenant", "team"], name="p_tmem_tnt_team_idx"),
                    models.Index(
                        fields=["tenant", "user_id"], name="p_tmem_tnt_user_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "team", "user_id"),
                        name="portal_team_member_tenant_team_user_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["tenant", "community"], name="portal_team_tenant_comm_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("tenant", "community", "name"),
                name="portal_team_tenant_comm_name_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "visibility"], name="portal_post_tenant_vis_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "community"], name="portal_post_tenant_comm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "team"], name="portal_post_tenant_team_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["tenant", "created_at"], name="portal_post_tenant_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portalprofile",
            index=models.Index(
                fields=["tenant", "user_id"], name="portal_profile_tenant_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user_id"), name="portal_profile_tenant_user_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["tenant", "community"], name="p_cmem_tnt_comm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["tenant", "user_id"], name="p_cmem_tnt_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="communitymembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "community", "user_id"),
                name="portal_comm_member_tenant_comm_user_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(fields=["tenant"], name="portal_community_tenant_idx"),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="portal_community_tenant_name_uniq"
            ),
        ),
    ]
