# Generated by Django 5.2.15 on 2026-09-30 15:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_portalauditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("applicant_user_id", models.UUIDField(db_index=True)),
                ("slug", models.SlugField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_by_user_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "portal_tenant_application",
                "indexes": [
                    models.Index(
                        fields=["applicant_user_id", "status"],
                        name="p_tapp_user_status_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantProvisioningOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "event_type",
                    models.CharField(default="tenant.owner.provision", max_length=64),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.tenantapplication",
                    ),
                ),
            ],
            options={
                "db_table": "portal_tenant_provisioning_outbox",
            },
        ),
        migrations.CreateModel(
            name="TenantSlugClaim",
            fields=[
                (
                    "slug",
                    models.SlugField(max_length=32, primary_key=True, serialize=False),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.tenantapplication",
                    ),
                ),
            ],
            options={
                "db_table": "portal_tenant_slug_claim",
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(default="active", max_length=16)),
                ("base_role", models.CharField(default="member", max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="portal.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "portal_tenant_membership",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user_id"), name="p_tenant_member_uniq"
                    )
                ],
            },
        ),
    ]
