# Generated by Django 5.2.8 on 2026-02-03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_outbox_feedlastseen_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("author_user_id", models.UUIDField()),
                ("title", models.CharField(blank=True, max_length=256)),
                ("body", models.TextField()),
                ("tags_json", models.JSONField(default=list)),
                ("media_json", models.JSONField(default=list)),
                ("visibility", models.CharField(choices=[("public", "public"), ("community", "community"), ("team", "team"), ("private", "private")], default="public", max_length=16)),
                ("scope_type", models.CharField(choices=[("GLOBAL", "GLOBAL"), ("TENANT", "TENANT"), ("COMMUNITY", "COMMUNITY"), ("TEAM", "TEAM"), ("SERVICE", "SERVICE")], default="TENANT", max_length=16)),
                ("scope_id", models.CharField(max_length=128)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("reactions_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "act_news_post",
            },
        ),
        migrations.CreateModel(
            name="NewsReaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("emoji", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField()),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="activity.newspost")),
            ],
            options={
                "db_table": "act_news_reaction",
            },
        ),
        migrations.CreateModel(
            name="NewsComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="activity.newspost")),
            ],
            options={
                "db_table": "act_news_comment",
            },
        ),
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(fields=["tenant_id", "created_at"], name="act_news_tnt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(fields=["tenant_id", "scope_type", "scope_id"], name="act_news_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="newsreaction",
            index=models.Index(fields=["tenant_id", "post"], name="act_news_react_post_idx"),
        ),
        migrations.AddConstraint(
            model_name="newsreaction",
            constraint=models.UniqueConstraint(fields=("post", "user_id", "emoji"), name="act_news_reaction_unique"),
        ),
        migrations.AddIndex(
            model_name="newscomment",
            index=models.Index(fields=["tenant_id", "post", "created_at"], name="act_news_comment_idx"),
        ),
    ]
