# Generated by Django 5.2.8 on 2026-02-06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_alter_newscomment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="activity.newscomment",
            ),
        ),
        migrations.AddField(
            model_name="newscomment",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="NewsCommentReaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="activity.newscomment",
                    ),
                ),
            ],
            options={
                "db_table": "act_news_comment_reaction",
            },
        ),
        migrations.AddIndex(
            model_name="newscomment",
            index=models.Index(
                fields=["tenant_id", "post", "parent", "created_at"],
                name="act_news_comment_parent_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="newscommentreaction",
            constraint=models.UniqueConstraint(
                fields=("comment", "user_id"),
                name="act_news_comment_reaction_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="newscommentreaction",
            index=models.Index(
                fields=["tenant_id", "comment"],
                name="act_news_comment_react_idx",
            ),
        ),
    ]
