# Generated by Django 5.2.8 on 2026-04-04 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0008_activityauditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPostView",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                (
                    "first_viewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="activity.newspost",
                    ),
                ),
            ],
            options={
                "db_table": "act_news_post_view",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "post"], name="act_news_view_post_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "user_id"], name="act_news_view_user_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user_id"), name="act_news_post_view_unique"
                    )
                ],
            },
        ),
    ]
