# Generated by Django 5.2.8 on 2025-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageModal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "button_text",
                    models.CharField(
                        default="OK", max_length=100, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "modal_type",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("success", "Успех"),
                            ("promo", "Промо"),
                        ],
                        default="info",
                        max_length=50,
                        verbose_name="Тип модалки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "display_once",
                    models.BooleanField(
                        default=False, verbose_name="Показать один раз"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала показа"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания показа"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок показа"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Модальное окно главной страницы",
                "verbose_name_plural": "Модальные окна главной страницы",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
