# Generated by Django 5.2.8 on 2026-01-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationvote',
            name='nomination',
            field=models.ForeignKey(db_column='nomination_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nominations.nomination'),
        ),
        migrations.AlterField(
            model_name='nominationvote',
            name='option',
            field=models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='nominations.nominationoption'),
        ),
    ]
